# Generated by Django 5.2.7 on 2025-11-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestamo_id', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('recibidoPor_id', models.IntegerField()),
                ('condicion', models.CharField(default='Bueno', max_length=100)),
                ('prestamo_vencido', models.BooleanField(default=False)),
                ('sancion_puntos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
